---
title: "Use PCAs to filter out outliers"
author: 
  - David lukacsovich^[University of Miami]
  - Lily Wang^[University of Miami]
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    highlight: pygments
    theme: yeti
    toc: true
    number_sections: true
    df_print: paged
    code_download: false
    toc_float:
      collapsed: yes
    toc_depth: 3
editor_options:
  chunk_output_type: inline    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set Up

## Load Libraries

```{r library}
suppressMessages({
  library(dplyr)
  library(irlba)
  library(SummarizedExperiment)
  library(parallel)
  library(doParallel)
})

base_dir <- "../../.."
analysis_dir <- file.path(base_dir, "AD_CR")
data_dir <- file.path(analysis_dir, "data/DNAm_Aplus/processed")
code_dir <- file.path(analysis_dir, "code", "functions")

source(file.path(code_dir, "run_pca.R"), local = TRUE)
```

## Load Data

```{r load}
dnam_data <- readRDS(file.path(data_dir, "Autosomal.RDS"))
```

# Define Functions

## Wrapper Function

```{r func_wrapper}
process_dataset <- function(
    dnam_data,
    outlier_cutoff = 3,
    pc_count = 5,
    pc_label = "NPC_",
    outlier_label = "is_outlier"
) {
  pca_res <- get_dnam_pca(
    dnam_data,
    outlier_cutoff,
    pc_count = pc_count, 
    pc_label = pc_label,
    outlier_label = outlier_label
  )
  dnam_data <- pca_res$dnam_data
  percentVar <- pca_res$percentVar
  pca_params <- pca_res$pca_params
  
  pca_df <- dnam_data %>%
    SummarizedExperiment::colData() %>%
    as.data.frame()
  
  dnam_data <- dnam_data[,!pca_df$is_outlier]
  
  list(
    dnam_data = dnam_data,
    pca_df = pca_df,
    percentVar = percentVar,
    pca_params = pca_params
  )
}
```

# Run PCA

```{r run}
pca_res <- process_dataset(
  dnam_data,
  outlier_cutoff = 3,
  pc_count = 5,
  pc_label = "NPC_",
  outlier_label = "is_outlier"
)
dnam_data <- pca_res$dnam_data
pca_df <- pca_res$pca_df %>%
  dplyr::mutate(age_split_by_tertiles = as.character(.data$age_split_by_tertiles))
percentVar <- pca_res$percentVar
pca_params <- pca_res$pca_params
```

# Create PCA Plot

```{r pca}
outlier_cutoff <- 3
message("There are a total of ", sum(pca_df$is_outlier), " outliers out of ", nrow(pca_df), " samples")

plot_pca(
  pca_df,
  "triple_Aplus", 
  "age_split_by_tertiles",
  percentVar,
  pca_params,
  outlier_cutoff,
  pc_label = "NPC_",
  outlier_label = "is_outlier"
)
plot_pca(
  pca_df,
  "triple_Aplus",
  "Gender",
  percentVar,
  pca_params,
  outlier_cutoff,
  pc_label = "NPC_",
  outlier_label = "is_outlier"
)
```

# Save

```{r save}
saveRDS(dnam_data, file.path(data_dir, "PCA.RDS"))
```

# Session Information

<details>
  <summary>**Session Info**</summary>
```{r session}
sessionInfo()
```
</details>
